### PR TITLE
Add comment logging in index.ts

### PR DESCRIPTION
**Pull request by kevinzunigacuellar**

### CODE REVIEW

**Comment by kevinzunigacuellar** [comment]
foo

**Comment by kevinzunigacuellar** [comment]
aosaso

**Comment by kevinzunigacuellar** [comment]
baaar

**Comment by Fryuni** [comment]
Hey

**Comment by samnj** [comment]
Messi > cr7

**Comment by kevinzunigacuellar** [comment]
fiz

**Comment by kevinzunigacuellar** [comment]
cat

**Comment by kevinzunigacuellar** [comment]
woo

**Comment by kevinzunigacuellar** [comment]
a

**Comment by kevinzunigacuellar** [comment]
fiz

**Comment by kevinzunigacuellar** [comment]
gimly

**Comment by kevinzunigacuellar** [comment]
!coauthors

**Comment by kevinzunigacuellar** [comment]
!coauthors

**Pull request closed without merging**
