### PR TITLE
feat: add coauthor string

### PR DESCRIPTION
**Pull request by kevinzunigacuellar**
## Description

This pull request introduces an automated action triggered by the addition of the `add-coauthors` label to any pull request. The action generates co-author strings based on the involved participants, simplifying the co-authorship process and fostering collaborative contributions.

### CODE REVIEW

**Comment by yanthomasdev** [comment]
something

**Comment by delucis** [comment]
I would also like something!

**Comment by kevinzunigacuellar** [comment]
```
		Co-authored-by: Yan Thomas <61414485+Yan-Thomas@users.noreply.github.com>
Co-authored-by: Chris Swithinbank <357379+delucis@users.noreply.github.com>
		```

**Comment by kevinzunigacuellar** [comment]
```
Co-authored-by: Yan Thomas <61414485+Yan-Thomas@users.noreply.github.com>
Co-authored-by: Chris Swithinbank <357379+delucis@users.noreply.github.com>
```

**Pull request merged**
